### ISSUE TITLE
package.json have --roots=\"<rootDir>\"which makes yarn coverage do not work

### ISSUE THREAD

**Issue by qingbolove** [penx/storybook-code-coverage#6]
It keeps telling that it could not recognize the folder path, please change it to something static, then we could quickly check this whole solution. Thank you!

**Comment by penx** [comment]
Did you run the following exactly as follows:

https://github.com/penx/storybook-code-coverage/blob/53ccef0618f6e65210ee6700ba9d3edac2b1b43f/README.md#L16-L20

If so,

- at what point does it fail?
- what version of node, yarn do you have?
- what OS are you on?

**Comment by qingbolove** [comment]
Thanks Penx, I think the reason is I am using a windows, which make "rm" and "mv" command do not work, I replace "rm" with "rimraf" I manual move the file, delete mv command it is ok now.

**Comment by penx** [comment]
Ah yes, that would be it, glad it's working now! If you want to open a PR that uses https://www.npmjs.com/package/rimraf instead of rm, I'll happily merge it
